### ISSUE TITLE
Support extracting sr.ht auth token from external source

### ISSUE THREAD

**Issue by rktjmp** [rktjmp/paperplanes.nvim#12]
![image](https://github.com/rktjmp/paperplanes.nvim/assets/866010/2a665a48-a32e-4292-be79-447a61a89f13)

**Comment by dchinmay2** [comment]
the current srht implementation needs to go anyway as it uses the legacy oauth api

**Comment by rktjmp** [comment]
I dont think PATs are being deprecated, just the old OAuth1 flow. OAuth2 flow isn't really compatible with us due to requiring a client (aka application) secret, and its tokens are only 24 hours. Would require each user to create their own oauth app, bunch of state book keeping for renewing tokens, etc.

I added support for `hut` via `provider_options = { command = "hut"}` (can drop the token key when using `hut`). The existing curl interface also remains supported.
