### ISSUE TITLE
GitHub gist support?

### ISSUE THREAD

**Issue by stefanvanburen** [rktjmp/paperplanes.nvim#14]
Could use [`gh gist create`](https://cli.github.com/manual/gh_gist_create) or probably the REST/GraphQL API. Feel free to close if you're not interested in supporting it, though.

**Comment by rktjmp** [comment]
Added in 6d13d50db59ce53a7991820b0c188715070ec656

```
https://gist.github.com/ (provider = "gist")
    command: "curl" (default) or "gh".
    token: PAT token string or function returning token string, required if command = "curl" | nil.
```

The use case for gists was a bit murky for me personally which is why I never added it, because they're a bit more permanent, allow updating them, etc. Probably it could suit a nicer interface for posting revisions.
